### ISSUE TITLE
Console error spam

### ISSUE THREAD

**Issue by SbirTeo** [Ben12345rocks/VotingPlugin#1201]
[23:12:25 WARN]: org.bukkit.plugin.IllegalPluginAccessException: Plugin attempted to register task while disabled
[23:12:25 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.validate(CraftScheduler.java:552)
[23:12:25 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.runTaskTimerAsynchronously(CraftScheduler.java:251)
[23:12:25 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.runTaskTimerAsynchronously(CraftScheduler.java:247)
[23:12:25 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.runTaskLaterAsynchronously(CraftScheduler.java:192)
[23:12:25 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.runTaskAsynchronously(CraftScheduler.java:161)
[23:12:25 WARN]:        at VotingPlugin.jar//com.bencodez.votingplugin.advancedcore.api.rewards.Reward.giveInjectedRewards(Reward.java:222)
[23:12:25 WARN]:        at VotingPlugin.jar//com.bencodez.votingplugin.advancedcore.api.rewards.Reward.giveRewardUser(Reward.java:378)
[23:12:25 WARN]:        at VotingPlugin.jar//com.bencodez.votingplugin.advancedcore.api.rewards.Reward.giveReward(Reward.java:336)
[23:12:25 WARN]:        at VotingPlugin.jar//com.bencodez.votingplugin.advancedcore.api.rewards.RewardHandler.giveReward(RewardHandler.java:494)
[23:12:25 WARN]:        at VotingPlugin.jar//com.bencodez.votingplugin.advancedcore.api.rewards.RewardHandler.giveReward(RewardHandler.java:456)
[23:12:25 WARN]:        at VotingPlugin.jar//com.bencodez.votingplugin.advancedcore.api.rewards.RewardBuilder.send(RewardBuilder.java:74)
[23:12:25 WARN]:        at VotingPlugin.jar//com.bencodez.votingplugin.votereminding.VoteReminding.giveReward(VoteReminding.java:49)
[23:12:25 WARN]:        at VotingPlugin.jar//com.bencodez.votingplugin.votereminding.VoteReminding.runRemind(VoteReminding.java:88)
[23:12:25 WARN]:        at VotingPlugin.jar//com.bencodez.votingplugin.votereminding.VoteReminding.checkRemind(VoteReminding.java:38)
[23:12:25 WARN]:        at VotingPlugin.jar//com.bencodez.votingplugin.votereminding.VoteReminding$1.run(VoteReminding.java:68)
[23:12:25 WARN]:        at java.base/java.util.TimerThread.mainLoop(Timer.java:556)
[23:12:25 WARN]:        at java.base/java.util.TimerThread.run(Timer.java:506)

**Comment by BenCodez** [comment]
When do you get that error? This any better?
https://bencodez.com/job/VotingPlugin/

**Comment by SbirTeo** [comment]
I disabled the votereminding and the console spam this error

Il Ven 29 Ott 2021, 23:15 Ben ***@***.***> ha scritto:

**Comment by BenCodez** [comment]
Did you reload the plugin (like disable and enable) with some plugin manager or /reload?

**Comment by SbirTeo** [comment]
Yes, I did. Plugman

Il Ven 29 Ott 2021, 23:20 Ben ***@***.***> ha scritto:

**Comment by BenCodez** [comment]
Then that's why it happened, don't use plugman. Just do a restart.

**Comment by SbirTeo** [comment]
Thank u, if i will encounter other problems i will ask u. Keep open this ticket for anoter day, please.
