### ISSUE TITLE
Problems with MySQL

### ISSUE THREAD

**Issue by Taracraft** [Ben12345rocks/VotingPlugin#1206]
**Versions**
Plugin version and spigot version
`VotingPlugin:
  Version: 'git-Paper-325 (MC: 1.17.1)'
  ServiceSites:
  - minecraft-server.eu
  - minecraft-serverlist.net
  - minecraft-servers.de
  - MCSL
  VoteParty:
    Total: 0
    Voted: []
  VotePartyExtraRequired: 140
PluginVersions:
  VotingPlugin: '6.7'
PrevDay: 14
PrevWeek: 47
Month: NOVEMBER
IntColumns:
- VotePartyVotes
- MilestoneCount
- MonthTotal
- AllTimeTotal
- DailyTotal
- WeeklyTotal
- Points
- DayVoteStreak
- BestDayVoteStreak
- WeekVoteStreak
- BestWeekVoteStreak
- MonthVoteStreak
- HighestDailyTotal
- HighestMonthlyTotal
- HighestWeeklyTotal
- LastMonthTotal
- BestMonthVoteStreak
LastUpdated: 1636920670692
`
**Relevant information**
Configs that relate to the issue in a pastebin.
`MySQL:
  Host: '127.0.0.1'
  # Default port is 3306
  Port: 3306
  Database: ''
  Username: ''
  Password: ''
  # Max number of connections
  MaxConnections: 1
  # Maxium size of caching mysql
  # -1 for no limit
  # Affecting this value may affect performance
  MaxSize: -1
  # Table name prefix, for use with mutliple servers
  Prefix: '117_'
  #UseSSL: false
  #PublicKeyRetrieval: false
`
**Context**
Context about the question/concern
`21:11:25 ERROR] [VotingPlugin] Failed to send query: ALTER TABLE 117_VotingPlugin_Users ADD COLUMN OfflineRewards1.17.1 text;
[21:11:25 WARN] java.sql.SQLSyntaxErrorException: Incorrect database name 'OfflineRewards1'
[21:11:25 WARN] at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
[21:11:25 WARN] at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
[21:11:25 WARN] at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:953)
[21:11:25 WARN] at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1092)
[21:11:25 WARN] at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1040)
[21:11:25 WARN] at com.mysql.cj.jdbc.ClientPreparedStatement.executeLargeUpdate(ClientPreparedStatement.java:1347)
[21:11:25 WARN] at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdate(ClientPreparedStatement.java:1025)
[21:11:25 WARN] at VotingPlugin.jar//com.bencodez.votingplugin.advancedcore.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61)
[21:11:25 WARN] at VotingPlugin.jar//com.bencodez.votingplugin.advancedcore.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java)
[21:11:25 WARN] at VotingPlugin.jar//com.bencodez.votingplugin.advancedcore.api.user.userstorage.mysql.api.queries.Query.executeUpdate(Query.java:151)
[21:11:25 WARN] at VotingPlugin.jar//com.bencodez.votingplugin.advancedcore.api.user.userstorage.mysql.MySQL.addColumn(MySQL.java:158)
[21:11:25 WARN] at VotingPlugin.jar//com.bencodez.votingplugin.advancedcore.api.user.userstorage.mysql.MySQL.checkColumn(MySQL.java:198)
[21:11:25 WARN] at VotingPlugin.jar//com.bencodez.votingplugin.advancedcore.api.user.userstorage.mysql.MySQL.update(MySQL.java:522)
[21:11:25 WARN] at VotingPlugin.jar//com.bencodez.votingplugin.advancedcore.api.user.UserData.setValues(UserData.java:516)
[21:11:25 WARN] at VotingPlugin.jar//com.bencodez.votingplugin.advancedcore.api.user.UserData.setValues(UserData.java:498)
[21:11:25 WARN] at VotingPlugin.jar//com.bencodez.votingplugin.advancedcore.api.user.usercache.UserDataCache.processChanges(UserDataCache.java:112)
[21:11:25 WARN] at VotingPlugin.jar//com.bencodez.votingplugin.advancedcore.api.user.usercache.UserDataCache$1.run(UserDataCache.java:125)
[21:11:25 WARN] at java.base/java.util.TimerThread.mainLoop(Timer.java:556)
[21:11:25 WARN] at java.base/java.util.TimerThread.run(Timer.java:506)
[21:11:25 ERROR] [VotingPlugin] Failed to send query: UPDATE 117_VotingPlugin_Users SET CheckWorld='false', OfflineRewards1.17.1='', LastOnline='1636920682638' WHERE uuid='c4310a50-1134-4ae7-ae84-bf81fb0b0d96';
[21:11:25 WARN] java.sql.SQLSyntaxErrorException: Unknown column 'OfflineRewards1.17.1' in 'field list'
[21:11:25 WARN] at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
[21:11:25 WARN] at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
[21:11:25 WARN] at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:953)
[21:11:25 WARN] at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1092)
[21:11:25 WARN] at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1040)
[21:11:25 WARN] at com.mysql.cj.jdbc.ClientPreparedStatement.executeLargeUpdate(ClientPreparedStatement.java:1347)
[21:11:25 WARN] at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdate(ClientPreparedStatement.java:1025)
[21:11:25 WARN] at VotingPlugin.jar//com.bencodez.votingplugin.advancedcore.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61)
[21:11:25 WARN] at VotingPlugin.jar//com.bencodez.votingplugin.advancedcore.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java)
[21:11:25 WARN] at VotingPlugin.jar//com.bencodez.votingplugin.advancedcore.api.user.userstorage.mysql.api.queries.Query.executeUpdate(Query.java:151)
[21:11:25 WARN] at VotingPlugin.jar//com.bencodez.votingplugin.advancedcore.api.user.userstorage.mysql.MySQL.update(MySQL.java:559)
[21:11:25 WARN] at VotingPlugin.jar//com.bencodez.votingplugin.advancedcore.api.user.UserData.setValues(UserData.java:516)
[21:11:25 WARN] at VotingPlugin.jar//com.bencodez.votingplugin.advancedcore.api.user.UserData.setValues(UserData.java:498)
[21:11:25 WARN] at VotingPlugin.jar//com.bencodez.votingplugin.advancedcore.api.user.usercache.UserDataCache.processChanges(UserDataCache.java:112)
[21:11:25 WARN] at VotingPlugin.jar//com.bencodez.votingplugin.advancedcore.api.user.usercache.UserDataCache$1.run(UserDataCache.java:125)
[21:11:25 WARN] at java.base/java.util.TimerThread.mainLoop(Timer.java:556)
[21:11:25 WARN] at java.base/java.util.TimerThread.run(Timer.java:506)
[21:12:19 ERROR] [VotingPlugin] Failed to send query: ALTER TABLE 117_VotingPlugin_Users ADD COLUMN AllSitesLast_1.17.1 text;
[21:12:19 WARN] java.sql.SQLSyntaxErrorException: Incorrect database name 'AllSitesLast_1'
[21:12:19 WARN] at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
[21:12:19 WARN] at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
[21:12:19 WARN] at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:953)
[21:12:19 WARN] at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1092)
[21:12:19 WARN] at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1040)
[21:12:19 WARN] at com.mysql.cj.jdbc.ClientPreparedStatement.executeLargeUpdate(ClientPreparedStatement.java:1347)
[21:12:19 WARN] at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdate(ClientPreparedStatement.java:1025)
[21:12:19 WARN] at VotingPlugin.jar//com.bencodez.votingplugin.advancedcore.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61)
[21:12:19 WARN] at VotingPlugin.jar//com.bencodez.votingplugin.advancedcore.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java)
[21:12:19 WARN] at VotingPlugin.jar//com.bencodez.votingplugin.advancedcore.api.user.userstorage.mysql.api.queries.Query.executeUpdate(Query.java:151)
[21:12:19 WARN] at VotingPlugin.jar//com.bencodez.votingplugin.advancedcore.api.user.userstorage.mysql.MySQL.addColumn(MySQL.java:158)
[21:12:19 WARN] at VotingPlugin.jar//com.bencodez.votingplugin.advancedcore.api.user.userstorage.mysql.MySQL.checkColumn(MySQL.java:198)
[21:12:19 WARN] at VotingPlugin.jar//com.bencodez.votingplugin.advancedcore.api.user.userstorage.mysql.MySQL.update(MySQL.java:522)
[21:12:19 WARN] at VotingPlugin.jar//com.bencodez.votingplugin.advancedcore.api.user.UserData.setValues(UserData.java:516)
[21:12:19 WARN] at VotingPlugin.jar//com.bencodez.votingplugin.advancedcore.api.user.UserData.setValues(UserData.java:498)
[21:12:19 WARN] at VotingPlugin.jar//com.bencodez.votingplugin.advancedcore.api.user.usercache.UserDataCache.processChanges(UserDataCache.java:112)
[21:12:19 WARN] at VotingPlugin.jar//com.bencodez.votingplugin.advancedcore.api.user.usercache.UserDataCache$1.run(UserDataCache.java:125)
[21:12:19 WARN] at java.base/java.util.TimerThread.mainLoop(Timer.java:556)
[21:12:19 WARN] at java.base/java.util.TimerThread.run(Timer.java:506)
[21:12:19 ERROR] [VotingPlugin] Failed to send query: UPDATE 117_VotingPlugin_Users SET AllTimeTotal='37', DailyTotal='4', VotePartyVotes='37', LastVotes='Vote4//1636920736743%line%Vote3//1636920733428%line%Vote2//1636920725079%line%Vote1//1636920718487', MilestoneCount='37', MonthTotal='16', WeeklyTotal='4', AllSitesLast_1.17.1='318' WHERE uuid='c4310a50-1134-4ae7-ae84-bf81fb0b0d96';
[21:12:19 WARN] java.sql.SQLSyntaxErrorException: Unknown column 'AllSitesLast_1.17.1' in 'field list'
[21:12:19 WARN] at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
[21:12:19 WARN] at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
[21:12:19 WARN] at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:953)
[21:12:19 WARN] at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1092)
[21:12:19 WARN] at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1040)
[21:12:19 WARN] at com.mysql.cj.jdbc.ClientPreparedStatement.executeLargeUpdate(ClientPreparedStatement.java:1347)
[21:12:19 WARN] at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdate(ClientPreparedStatement.java:1025)
[21:12:19 WARN] at VotingPlugin.jar//com.bencodez.votingplugin.advancedcore.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61)
[21:12:19 WARN] at VotingPlugin.jar//com.bencodez.votingplugin.advancedcore.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java)
[21:12:19 WARN] at VotingPlugin.jar//com.bencodez.votingplugin.advancedcore.api.user.userstorage.mysql.api.queries.Query.executeUpdate(Query.java:151)
[21:12:19 WARN] at VotingPlugin.jar//com.bencodez.votingplugin.advancedcore.api.user.userstorage.mysql.MySQL.update(MySQL.java:559)
[21:12:19 WARN] at VotingPlugin.jar//com.bencodez.votingplugin.advancedcore.api.user.UserData.setValues(UserData.java:516)
[21:12:19 WARN] at VotingPlugin.jar//com.bencodez.votingplugin.advancedcore.api.user.UserData.setValues(UserData.java:498)
[21:12:19 WARN] at VotingPlugin.jar//com.bencodez.votingplugin.advancedcore.api.user.usercache.UserDataCache.processChanges(UserDataCache.java:112)
[21:12:19 WARN] at VotingPlugin.jar//com.bencodez.votingplugin.advancedcore.api.user.usercache.UserDataCache$1.run(UserDataCache.java:125)
[21:12:19 WARN] at java.base/java.util.TimerThread.mainLoop(Timer.java:556)
[21:12:19 WARN] at java.base/java.util.TimerThread.run(Timer.java:506)
[21:12:19 ERROR] [VotingPlugin] Failed to send query: UPDATE 117_VotingPlugin_Users SET OfflineRewards1.17.1='VoteParty_Rewards%placeholders%VotesRequired%pair%20%entry%ExecDate%pair%1636920736730%entry%Date%pair%Sun, 14 Nov 2021 21:12' WHERE uuid='4ff7f0f9-7b15-40cb-9381-38e88d745a5e';
[21:12:19 WARN] java.sql.SQLSyntaxErrorException: Unknown column 'OfflineRewards1.17.1' in 'field list'
[21:12:19 WARN] at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
[21:12:19 WARN] at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
[21:12:19 WARN] at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:953)
[21:12:19 WARN] at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1092)
[21:12:19 WARN] at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1040)
[21:12:19 WARN] at com.mysql.cj.jdbc.ClientPreparedStatement.executeLargeUpdate(ClientPreparedStatement.java:1347)
[21:12:19 WARN] at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdate(ClientPreparedStatement.java:1025)
[21:12:19 WARN] at VotingPlugin.jar//com.bencodez.votingplugin.advancedcore.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61)
[21:12:19 WARN] at VotingPlugin.jar//com.bencodez.votingplugin.advancedcore.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java)
[21:12:19 WARN] at VotingPlugin.jar//com.bencodez.votingplugin.advancedcore.api.user.userstorage.mysql.api.queries.Query.executeUpdate(Query.java:151)
[21:12:19 WARN] at VotingPlugin.jar//com.bencodez.votingplugin.advancedcore.api.user.userstorage.mysql.MySQL.update(MySQL.java:559)
[21:12:19 WARN] at VotingPlugin.jar//com.bencodez.votingplugin.advancedcore.api.user.UserData.setValues(UserData.java:516)
[21:12:19 WARN] at VotingPlugin.jar//com.bencodez.votingplugin.advancedcore.api.user.UserData.setValues(UserData.java:498)
[21:12:19 WARN] at VotingPlugin.jar//com.bencodez.votingplugin.advancedcore.api.user.usercache.UserDataCache.processChanges(UserDataCache.java:112)
[21:12:19 WARN] at VotingPlugin.jar//com.bencodez.votingplugin.advancedcore.api.user.usercache.UserDataCache$1.run(UserDataCache.java:125)
[21:12:19 WARN] at java.base/java.util.TimerThread.mainLoop(Timer.java:556)
[21:12:19 WARN] at java.base/java.util.TimerThread.run(Timer.java:506)
[21:12:19 ERROR] [VotingPlugin] Failed to send query: UPDATE 117_VotingPlugin_Users SET OfflineRewards1.17.1='VoteParty_Rewards%placeholders%VotesRequired%pair%20%entry%ExecDate%pair%1636920736738%entry%Date%pair%Sun, 14 Nov 2021 21:12' WHERE uuid='8f4deb4a-4460-4060-b49b-0c235e742b7c';
[21:12:19 WARN] java.sql.SQLSyntaxErrorException: Unknown column 'OfflineRewards1.17.1' in 'field list'
[21:12:19 WARN] at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
[21:12:19 WARN] at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
[21:12:19 WARN] at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:953)
[21:12:19 WARN] at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1092)
[21:12:19 WARN] at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1040)
[21:12:19 WARN] at com.mysql.cj.jdbc.ClientPreparedStatement.executeLargeUpdate(ClientPreparedStatement.java:1347)
[21:12:19 WARN] at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdate(ClientPreparedStatement.java:1025)
[21:12:19 WARN] at VotingPlugin.jar//com.bencodez.votingplugin.advancedcore.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61)
[21:12:19 WARN] at VotingPlugin.jar//com.bencodez.votingplugin.advancedcore.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java)
[21:12:19 WARN] at VotingPlugin.jar//com.bencodez.votingplugin.advancedcore.api.user.userstorage.mysql.api.queries.Query.executeUpdate(Query.java:151)
[21:12:19 WARN] at VotingPlugin.jar//com.bencodez.votingplugin.advancedcore.api.user.userstorage.mysql.MySQL.update(MySQL.java:559)
[21:12:19 WARN] at VotingPlugin.jar//com.bencodez.votingplugin.advancedcore.api.user.UserData.setValues(UserData.java:516)
[21:12:19 WARN] at VotingPlugin.jar//com.bencodez.votingplugin.advancedcore.api.user.UserData.setValues(UserData.java:498)
[21:12:19 WARN] at VotingPlugin.jar//com.bencodez.votingplugin.advancedcore.api.user.usercache.UserDataCache.processChanges(UserDataCache.java:112)
[21:12:19 WARN] at VotingPlugin.jar//com.bencodez.votingplugin.advancedcore.api.user.usercache.UserDataCache$1.run(UserDataCache.java:125)
[21:12:19 WARN] at java.base/java.util.TimerThread.mainLoop(Timer.java:556)
[21:12:19 WARN] at java.base/java.util.TimerThread.run(Timer.java:506)`

**Comment by BenCodez** [comment]
Bungee setup?

**Comment by Taracraft** [comment]
Yes

**Comment by BenCodez** [comment]
send your bungeesettings.yml

and what bungee setup?

**Comment by Taracraft** [comment]
Votes are Working but Wrong Database? or Wrong Table? i have make Preffix for Each Vanilla Realm

**Comment by Taracraft** [comment]
Waterfull with Paper

**Comment by BenCodez** [comment]
https://github.com/BenCodez/VotingPlugin/wiki/Bungeecord-Setups

What bungee setup from there?

**Comment by Taracraft** [comment]
`server_connect_timeout: 50000
listeners:
- query_port: 25577
  motd: '&1Bad-Timing Connector'
  tab_list: GLOBAL_PING
  query_enabled: false
  proxy_protocol: false
  forced_hosts:
    pvp.md-5.net: pvp
  ping_passthrough: false
  priorities:
  - 1.16.5
  bind_local_address: true
  host: 

  max_players: 1000
  tab_size: 60
  force_default_server: false
remote_ping_cache: -1
network_compression_threshold: 256
permissions:
  default:
  - bungeecord.command.server
  - bungeecord.command.list
  admin:
  - bungeecord.command.alert
  - bungeecord.command.end
  - bungeecord.command.ip
  - bungeecord.command.reload
log_pings: true
connection_throttle_limit: 3
prevent_proxy_connections: false
timeout: 30000
player_limit: -1
ip_forward: true
groups:
  Taracraft:
  - Admin
remote_ping_timeout: 5000
connection_throttle: 40000
log_commands: true
stats: efb9a79b-8f93-4533-9a94-2d73372a6b56
online_mode: true
forge_support: true
disabled_commands:
- disabledcommandhere
servers:
  1.16.5:
    motd: '&1BT 1.16.5'
    address: 
    restricted: false
  ATM3:
    motd: '&1BT ATM3'
    address: 
    restricted: false
  ATM6:
    motd: '&1BT ATM6'
    address: 
    restricted: false
  1.17.1:
    motd: '&1BT 1.17.1'
    address: 
    restricted: false
`

**Comment by Taracraft** [comment]
Pluginmessages

**Comment by BenCodez** [comment]
Send your BungeeSettings.yml? You should not set a prefix for every server either

**Comment by Taracraft** [comment]
`# Set bungeecoord to true on servers on the network (In VotingPlugin)
# Set server name in each server related to what it is on bungee
#
# MYSQL Required on all setups
# MYSQL INFO --------------------------
Host: '127.0.0.1'
# Default port is 3306
Port: 3306 
Database: ''
Username: ''
Password: ''
# Max number of connections
MaxConnections: 1
# Maxium size of caching mysql
# -1 for no limit
# Affecting this value may affect performance
MaxSize: -1
# Table name prefix, for use with mutliple servers
Prefix: ''
#UseSSL: false
#PublicKeyRetrieval: false

Debug: false
# Have a reward on each server
# If false, will send to online server only
SendVotesToAllServers: true
# List of servers the plugin won't send the vote to
# Uses names from bungeecoord config, only needed for non SOCKETS setup
BlockedServers:
- hub

# What type of bungee setup
# Requires restart and set on all servers
# https://github.com/BenCodez/VotingPlugin/wiki/Bungeecoord-Setups
# Available:
# SOCKETS 
# PLUGINMESSAGING 
# MYSQL
BungeeMethod: MYSQL

# If false, votes will be checked if user is a valid player that has joined to server
# Works for PLUGINMESSAGING and SOCKETS methods only
# This requires spigot servers AllowUnJoined to be set to true in Config.yml
AllowUnJoined: true

# Points to give on vote
PointsOnVote: 1

# If true, bungee will handle adding totals
# If false, spigot servers will EACH set their own totals
# If false, AllowUnJoined should false on bungee, spigot servers will handle that
# Recommened to leave true, setting to false setups are currently unsupported
BungeeManageTotals: true

# Tell servers to broadcast
# Set DisableBroadcast to true on spigot servers (BungeeSettings.yml) as well
Broadcast: true

# ----------------------------
# PLUGINMESSAGING Settings
# ----------------------------

# Applies to PLUGINMESSAGING only
# Votes will be forwarded when specific player is online
WaitForUserOnline: false

# ----------------------------
# SOCKET Settings
# ONLY for SOCKET method
# ----------------------------

# Server to send vote to if player is offline
FallBackServer: 1.16.5

# Bungee communication, Add this to each spigot server
# For socket method
BungeeServer:
  Host: '127.0.0.1'
  Port: 1297
  
# Bungee communication, add each spigot server here
# For socket method
SpigotServers:
  1.16.5:
    Host: '127.0.0.1'
    Port: 1298
  1.17.1:
    Host: '127.0.0.1'
    Port: 1999`

**Comment by BenCodez** [comment]
Use pastebin to send files, not just pasting them here

**Comment by Taracraft** [comment]
https://pastebin.com/38kKWhyB

**Comment by BenCodez** [comment]
send your bungeesettings.yml on spigot server, that's bungeeconfig.yml

**Comment by Taracraft** [comment]
https://pastebin.com/CZihpBQD

**Comment by Taracraft** [comment]
from 2nd also?

**Comment by BenCodez** [comment]
Server: 1.17.1

You need to put the server name that's in bungee

**Comment by Taracraft** [comment]
it is set on bungee or i  miss understand you?

**Comment by BenCodez** [comment]
In bungee you set each server name, you need to match that in bungeesettings.yml

**Comment by BenCodez** [comment]
and disable this PerServerRewards: true

**Comment by Taracraft** [comment]
![image](https://user-images.githubusercontent.com/90864484/141698194-96fd3b6e-79fb-4dd7-b51b-45f5c3ce5acc.png)
i Think the 1.17.1 before Bunge is Wrong?

**Comment by Taracraft** [comment]
> and disable this PerServerRewards: true

this is the reason becuase i got 2 rewards each server?

**Comment by BenCodez** [comment]
What? you need to change what I said

**Comment by Taracraft** [comment]
ok i try thank you
