### ISSUE TITLE
RuntimeException on login - UserDataCache

### ISSUE THREAD

**Issue by mibby** [Ben12345rocks/VotingPlugin#1212]
**Versions**
VotingPlugin dev 310
Paper dev 81 (Spigot 1.18.1)

Downgrading to dev 307 resolves the issue.

**Describe the bug**
```
[07:19:13] [Server thread/INFO]: player[/] logged in with entity id 923 at ([spawn]-1648.5920533572223, 39.0, -1332.35317261983)
[07:19:15] [Craft Scheduler Thread - 36 - VotingPlugin/WARN]: java.lang.RuntimeException
[07:19:15] [Craft Scheduler Thread - 36 - VotingPlugin/WARN]: 	at VotingPlugin.jar//com.bencodez.votingplugin.advancedcore.api.user.usercache.UserDataCache.cache(UserDataCache.java:64)
[07:19:15] [Craft Scheduler Thread - 36 - VotingPlugin/WARN]: 	at VotingPlugin.jar//com.bencodez.votingplugin.advancedcore.api.user.usercache.UserDataManager.cacheUser(UserDataManager.java:71)
[07:19:15] [Craft Scheduler Thread - 36 - VotingPlugin/WARN]: 	at VotingPlugin.jar//com.bencodez.votingplugin.advancedcore.listeners.PlayerJoinEvent.onJoin(PlayerJoinEvent.java:38)
[07:19:15] [Craft Scheduler Thread - 36 - VotingPlugin/WARN]: 	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor469.execute(Unknown Source)
[07:19:15] [Craft Scheduler Thread - 36 - VotingPlugin/WARN]: 	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
[07:19:15] [Craft Scheduler Thread - 36 - VotingPlugin/WARN]: 	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76)
[07:19:15] [Craft Scheduler Thread - 36 - VotingPlugin/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[07:19:15] [Craft Scheduler Thread - 36 - VotingPlugin/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628)
[07:19:15] [Craft Scheduler Thread - 36 - VotingPlugin/WARN]: 	at VotingPlugin.jar//com.bencodez.votingplugin.advancedcore.listeners.PlayerJoinEvent$1.run(PlayerJoinEvent.java:78)
[07:19:15] [Craft Scheduler Thread - 36 - VotingPlugin/WARN]: 	at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:101)
[07:19:15] [Craft Scheduler Thread - 36 - VotingPlugin/WARN]: 	at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[07:19:15] [Craft Scheduler Thread - 36 - VotingPlugin/WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[07:19:15] [Craft Scheduler Thread - 36 - VotingPlugin/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[07:19:15] [Craft Scheduler Thread - 36 - VotingPlugin/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[07:19:15] [Craft Scheduler Thread - 36 - VotingPlugin/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
```

**To Reproduce**
1. Connect to server
2. Error on login

**Expected behavior**
No error.

**Comment by BenCodez** [comment]
https://bencodez.com/job/VotingPlugin/ left that in from debugging.
