### ISSUE TITLE
Error processing change of day event

### ISSUE THREAD

**Issue by GTP95** [Ben12345rocks/VotingPlugin#1229]
**Versions**
VotingPlugin v6.8.3 on bukkit-1.18.1-R0.1-SNAPSHOT

**Describe the bug**
Looking at the console output, seems that the plugin is facing an issue during the processing of a day change event

**To Reproduce**
Look in the server's console what happened somewhat near midnight

**Expected behavior**
No error message

**Screenshots/Configs**
Here is a copy&paste of the stacktrace:
```BASH

[22:14:37] [Timer-4/ERROR]: Could not pass event DateChangedEvent to VotingPlugin v6.8.3
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[bukkit-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[bukkit-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:588) [bukkit-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:575) [bukkit-1.18.1-R0.1-SNAPSHOT.jar:?]
        at com.bencodez.votingplugin.advancedcore.api.time.TimeChecker.forceChanged(TimeChecker.java:74) [VotingPlugin.jar:?]
        at com.bencodez.votingplugin.advancedcore.api.time.TimeChecker.update(TimeChecker.java:214) [VotingPlugin.jar:?]
        at com.bencodez.votingplugin.advancedcore.api.time.TimeChecker$2.run(TimeChecker.java:160) [VotingPlugin.jar:?]
        at java.util.TimerThread.mainLoop(Timer.java:566) [?:?]
        at java.util.TimerThread.run(Timer.java:516) [?:?]
Caused by: java.lang.NoClassDefFoundError: net/md_5/bungee/api/chat/BaseComponent
        at com.bencodez.votingplugin.advancedcore.api.backup.BackupHandle.checkOldBackups(BackupHandle.java:27) ~[?:?]
        at com.bencodez.votingplugin.advancedcore.api.backup.BackupHandle.onPostDateChange(BackupHandle.java:45) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:300) ~[bukkit-1.18.1-R0.1-SNAPSHOT.jar:?]
        ... 8 more
Caused by: java.lang.ClassNotFoundException: net.md_5.bungee.api.chat.BaseComponent
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:147) ~[bukkit-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:99) ~[bukkit-1.18.1-R0.1-SNAPSHOT.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        at com.bencodez.votingplugin.advancedcore.api.backup.BackupHandle.checkOldBackups(BackupHandle.java:27) ~[?:?]
        at com.bencodez.votingplugin.advancedcore.api.backup.BackupHandle.onPostDateChange(BackupHandle.java:45) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:300) ~[bukkit-1.18.1-R0.1-SNAPSHOT.jar:?]
        ... 8 more
[22:14:37] [Timer-4/INFO]: [VotingPlugin] Finished processing day changes

```

**Additional context**
Got this error while still configuring the plugin

**Comment by BenCodez** [comment]
Are you not using spigot?

**Comment by GTP95** [comment]
No, I'm using bukkit. Is only Spigot supported?

**Comment by BenCodez** [comment]
Use spigot

**Comment by GTP95** [comment]
Fixed by migrating to Spigot, thanks.
