### ISSUE TITLE
Error starting plugin

### ISSUE THREAD

**Issue by GTP95** [Ben12345rocks/VotingPlugin#1230]
**Versions**
VotingPlugin v6.8.3 on craftbukkit-1.18.1-R0.1-SNAPSHOT

**Describe the bug**
Got an error about a missing class while starting the server
**To Reproduce**
Download the plugin and start the server

**Expected behavior**
No error while starting the server
**Screenshots/Configs**
Here is a copy&paste of the error:
```BASH
[23:41:47] [Craft Scheduler Thread - 0/WARN]: [VotingPlugin] Plugin VotingPlugin v6.8.3 generated an exception while executing task 14
java.lang.NoClassDefFoundError: net/md_5/bungee/api/chat/BaseComponent
        at com.bencodez.votingplugin.advancedcore.api.item.ItemBuilder.setName(ItemBuilder.java:956) ~[?:?]
        at com.bencodez.votingplugin.advancedcore.api.inventory.BInventoryButton.<init>(BInventoryButton.java:68) ~[?:?]
        at com.bencodez.votingplugin.commands.CommandLoader$79$1$1.<init>(CommandLoader.java:1549) ~[?:?]
        at com.bencodez.votingplugin.commands.CommandLoader$79$1.run(CommandLoader.java:1548) ~[?:?]
        at com.bencodez.votingplugin.advancedcore.thread.Thread$ReadThread.run(Thread.java:48) ~[?:?]
        at com.bencodez.votingplugin.advancedcore.thread.Thread.run(Thread.java:101) ~[?:?]
        at com.bencodez.votingplugin.commands.CommandLoader$79.run(CommandLoader.java:1542) ~[?:?]
        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:77) ~[craftbukkit-1.18.1-R0.1-SNAPSHOT.jar:3426-Bukkit-febaa1c]
        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) [craftbukkit-1.18.1-R0.1-SNAPSHOT.jar:3426-Bukkit-febaa1c]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.ClassNotFoundException: net.md_5.bungee.api.chat.BaseComponent
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:147) ~[bukkit-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:99) ~[bukkit-1.18.1-R0.1-SNAPSHOT.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        ... 12 more

Add any other context about the problem here.

**Comment by BenCodez** [comment]
related to #1229
