### ISSUE TITLE
Exception while handling vote event

### ISSUE THREAD

**Issue by GTP95** [Ben12345rocks/VotingPlugin#1231]
**Versions**
VotingPlugin v6.8.3 on bukkit-1.18.1-R0.1-SNAPSHOT

**Describe the bug**
An exception occurred while processing a vote I made on a server list to test my configuration

**To Reproduce**
Configure the plugin following the steps detailed in the wiki. I can provide my full configuration if needed

**Expected behavior**
The vote gets processed without raising exceptions

**Screenshots/Configs**
Here is a copy&paste of the exception:
```BASH

[00:04:41] [Votifier NIO worker/INFO]: [Votifier] Got a protocol v1 vote record from /45.33.29.47:45270 -> Vote (from:MCSL username:7heKiller address:80.57.205.25 timeS
tamp:1645920281 additionalData:null)
[00:04:41] [Server thread/INFO]: [VotingPlugin] Received a vote from service site 'MCSL' by player '7heKiller'!
[00:04:41] [Craft Scheduler Thread - 4/WARN]: [VotingPlugin] VoteSite with service site 'MCSL' does not exist, attempting to generaterate...
[00:04:41] [Craft Scheduler Thread - 4/WARN]: [VotingPlugin] VoteSite MCSL does not exist with the servicesite 'MCSL', creating one, set AutoCreateVoteSites to false to
 prevent this
[00:04:41] [Craft Scheduler Thread - 4/WARN]: [VotingPlugin] VoteSites.MCSL is not a configuration section
[00:04:41] [Craft Scheduler Thread - 4/INFO]: [VotingPlugin] Current known service sites: MCSL
[00:04:41] [Craft Scheduler Thread - 4/ERROR]: Could not pass event PlayerVoteEvent to VotingPlugin v6.8.3
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[bukkit-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[bukkit-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:588) [bukkit-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:575) [bukkit-1.18.1-R0.1-SNAPSHOT.jar:?]
        at com.bencodez.votingplugin.listeners.VotiferEvent$1.run(VotiferEvent.java:105) [VotingPlugin.jar:?]
        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:77) [craftbukkit-1.18.1-R0.1-SNAPSHOT.jar:3426-Bukkit-febaa1c]
        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) [craftbukkit-1.18.1-R0.1-SNAPSHOT.jar:3426-Bukkit-febaa1c]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.NoClassDefFoundError: net/md_5/bungee/api/chat/BaseComponent
        at com.bencodez.votingplugin.user.UserManager.getVotingPluginUser(UserManager.java:98) ~[?:?]
        at com.bencodez.votingplugin.listeners.PlayerVoteListener.onplayerVote(PlayerVoteListener.java:107) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:300) ~[bukkit-1.18.1-R0.1-SNAPSHOT.jar:?]
        ... 9 more
Caused by: java.lang.ClassNotFoundException: net.md_5.bungee.api.chat.BaseComponent
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:147) ~[bukkit-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:99) ~[bukkit-1.18.1-R0.1-SNAPSHOT.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        at com.bencodez.votingplugin.user.UserManager.getVotingPluginUser(UserManager.java:98) ~[?:?]
        at com.bencodez.votingplugin.listeners.PlayerVoteListener.onplayerVote(PlayerVoteListener.java:107) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:300) ~[bukkit-1.18.1-R0.1-SNAPSHOT.jar:?]
        ... 9 more

```

**Comment by BenCodez** [comment]
related to #1229
