### ISSUE TITLE
Duplicate Voting

### ISSUE THREAD

**Issue by RocketManKian** [Ben12345rocks/VotingPlugin#1240]
**Versions**
Plugin: 6.8.4
Server: git-Purpur-1609 (MC: 1.18.2)

**Describe the bug**
When Players vote it seems there is a chance for the Vote to send through twice, meaning that the Player gets x2 the Rewards they're supposed to. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Install 'VotingPlugin' on 2 Servers apart of the same Bungeecord Network.
2. Setup 'NuVotifier' to forward with 'pluginMessaging'.
3. Attempt to Vote and the vote will send through twice.

**Expected behaviour**
The vote for each site to only send once.

**Screenshots/Configs**
![image](https://user-images.githubusercontent.com/47107486/163727236-515d0c7b-b7d6-4e96-96e8-5d4710fbda7a.png)
`VoteSites:
  # VoteSite key
  # Used for saving data for votesites
  # Use a short name if you can
  PlanetMinecraft:
    Enabled: true
    ServiceSite: planetminecraft.com
    VoteURL: https://www.planetminecraft.com/server/fortune-craft-5468230/
    VoteDelay: 24
    DisplayItem:
      Material: GOLD_INGOT
      Amount: 1
    Rewards:
      Commands:
      - 'broadcast &b%player% &7just voted on &6&l%ServiceSite%!'
      - 'adjustclaimblocks %player% 50'
      - 'msg %player% You have just been granted 50 Claim Blocks!'
  TopMinecraftServers:
    Enabled: true
    ServiceSite: topminecraftservers.org
    VoteURL: https://topminecraftservers.org/server/26663
    VoteDelay: 24
    DisplayItem:
      Material: GOLD_INGOT
      Amount: 1
    Rewards:
      Commands:
      - 'broadcast &b%player% &7just voted on &6&l%ServiceSite%!'
      - 'adjustclaimblocks %player% 50'
      - 'msg %player% You have just been granted 50 Claim Blocks!'
# Reward for any site
# Similar to AnySiteReward
# This requires the site to be configured in order to get the reward.
EverySiteReward: {}`

**Additional context**
N/A

**Comment by BenCodez** [comment]
Is the server getting the vote twice? You can set waituntilvotedelay to true (option in default votesites.yml) to prevent duplicates

**Comment by RocketManKian** [comment]
Hey! Thanks for the rapid response. Unfortunately I don't appear to see this in my VoteSites.yml nor on the Wiki https://github.com/BenCodez/VotingPlugin/wiki/Adding-VoteSites

**Comment by BenCodez** [comment]
https://github.com/BenCodez/VotingPlugin/blob/master/VotingPlugin/Resources/VoteSites.yml

**Comment by RocketManKian** [comment]
Awesome thank you! I have applied that now. The weirdest thing is that I don't see any duplicate voting being sent in the Bungeecord Console, like it's only receiving and sending the vote once which is strange as to why this issue might be occuring

**Comment by RocketManKian** [comment]
> https://github.com/BenCodez/VotingPlugin/blob/master/VotingPlugin/Resources/VoteSites.yml

Hey there!

Sorry one more thing on a completely different topic. I am setting up a system to post Votes into a Discord Channel. I'm just wondering what the event is called for when you receive the Vote. Thanks!

**Comment by BenCodez** [comment]
Just PlayerVoteEvent, but not one for when you get the rewards when you login

**Comment by RocketManKian** [comment]
Perfect! And what method should I use to retrieve the Website in which the Player voted on?

**Comment by BenCodez** [comment]
Using the event?

**Comment by RocketManKian** [comment]
Yep. So for example "event.getPlayer().toString()" would get the Player name

**Comment by BenCodez** [comment]
event.getVoteSite() or event.getServiceSite() - just use tab complete on event.get

**Comment by RocketManKian** [comment]
Thank you! That worked

**Comment by RocketManKian** [comment]
Hey there!

Unfortunately I'm now having a different issue. When a player votes on a site, it only gives rewards on one of the two servers. On the server where it fails it says this in console.

[01:13:33 INFO]: [VotingPlugin] Received a vote from service site 'TopMinecraftServers' by player 'TrappedHeart'!
[01:13:33 INFO]: [VotingPlugin] TrappedHeart must wait until votedelay is over, ignoring vote

**Comment by BenCodez** [comment]
Oh you have 2 servers, that's probably how your getting double rewards.

Follow this guide: https://github.com/BenCodez/VotingPlugin/wiki/Bungee-Setup-PLUGINMESSAGING

**Comment by RocketManKian** [comment]
Thank you! It appears to be working as intended now, will let you know otherwise.

**Comment by RocketManKian** [comment]
I think I may have Jinxed it, so when I tested it working last night I had yet to remove Votifier from the child servers, but I have now done that and I appear to be getting this error.

`[19:57:10 ERROR]: Could not pass event PlayerVoteEvent to VotingPlugin v6.8.4
java.lang.NoClassDefFoundError: com/vexsoftware/votifier/model/VotifierEvent
        at com.bencodez.votingplugin.listeners.BungeeVotifierEvent.send(BungeeVotifierEvent.java:13) ~[VotingPlugin.jar:?]
        at com.bencodez.votingplugin.listeners.PlayerVoteListener.onplayerVote(PlayerVoteListener.java:73) ~[VotingPlugin.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor269.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:git-Purpur-1609]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:631) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at com.bencodez.votingplugin.user.VotingPluginUser$3.run(VotingPluginUser.java:224) ~[VotingPlugin.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.18.2.jar:git-Purpur-1609]
        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[purpur-1.18.2.jar:git-Purpur-1609]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[purpur-1.18.2.jar:git-Purpur-1609]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ClassNotFoundException: com.vexsoftware.votifier.model.VotifierEvent
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:153) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:105) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        ... 14 more`

**Comment by RocketManKian** [comment]
Nvm! My bad. I had 'Trigger Votifier Event' enabled 😅
