### ISSUE TITLE
invaild skull

### ISSUE THREAD

**Issue by MrNinja008** [Ben12345rocks/VotingPlugin#1241]
**Versions**
Plugin version and spigot version.
6.8.4 spigot 1.18.2

**Describe the bug**
invaild skull type error after server has started and i added a flag to debug it and it showed voting plugin

**To Reproduce**
idk to reproduce but it just spams my console with your plugin name

**Expected behavior**

**Screenshots/Configs**
If applicable, add screenshots to help explain your problem and/or configs relating to the issue.

[09:19:47 ERROR]: Uncaught exception in thread Profile Lookup Executor #10
java.lang.RuntimeException: Original profile: 'com.mojang.authlib.GameProfile@53bba8e4[id=<null>,name=.IamHemant6720,properties={},legacy=false]'
        at net.minecraft.world.level.block.entity.SkullBlockEntity.lambda$updateGameprofile$7(SkullBlockEntity.java:192) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.IllegalArgumentException: Name and ID cannot both be blank
        at com.mojang.authlib.GameProfile.<init>(GameProfile.java:26) ~[authlib-3.3.39.jar:?]
        at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillGameProfile(YggdrasilMinecraftSessionService.java:200) ~[authlib-3.3.39.jar:?]
        at com.destroystokyo.paper.profile.PaperMinecraftSessionService.fillGameProfile(PaperMinecraftSessionService.java:38) ~[pufferfish-1.18.2.jar:git-Pufferfish-60]
        at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillProfileProperties(YggdrasilMinecraftSessionService.java:187) ~[authlib-3.3.39.jar:?]
        at com.destroystokyo.paper.profile.PaperMinecraftSessionService.fillProfileProperties(PaperMinecraftSessionService.java:31) ~[pufferfish-1.18.2.jar:git-Pufferfish-60]
        at net.minecraft.world.level.block.entity.SkullBlockEntity.lambda$updateGameprofile$4(SkullBlockEntity.java:170) ~[?:?]
        at net.minecraft.Util.ifElse(Util.java:427) ~[?:?]
        at net.minecraft.world.level.block.entity.SkullBlockEntity.lambda$updateGameprofile$7(SkullBlockEntity.java:167) ~[?:?]
        ... 3 more
        Suppressed: java.lang.Throwable: updateGameprofile caller debug trace
                at net.minecraft.world.level.block.entity.SkullBlockEntity.updateGameprofile(SkullBlockEntity.java:162) ~[?:?]
                at net.minecraft.world.level.block.entity.SkullBlockEntity.updateGameprofile(SkullBlockEntity.java:155) ~[?:?]
                at org.bukkit.craftbukkit.v1_18_R2.inventory.CraftMetaSkull.applyToItem(CraftMetaSkull.java:94) ~[pufferfish-1.18.2.jar:git-Pufferfish-60]
                at org.bukkit.craftbukkit.v1_18_R2.inventory.CraftItemStack.setItemMeta(CraftItemStack.java:553) ~[pufferfish-1.18.2.jar:git-Pufferfish-60]
                at org.bukkit.craftbukkit.v1_18_R2.inventory.CraftItemStack.asNMSCopy(CraftItemStack.java:42) ~[pufferfish-1.18.2.jar:git-Pufferfish-60]
                at jdk.internal.reflect.GeneratedMethodAccessor50.invoke(Unknown Source) ~[?:?]
                at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
                at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
                at com.bencodez.votingplugin.advancedcore.api.skull.SkullThread$ReadThread.load(SkullThread.java:40) ~[VotingPlugin.jar:?]
                at com.bencodez.votingplugin.advancedcore.api.skull.SkullThread$ReadThread.runBackgroundCheck(SkullThread.java:87) ~[VotingPlugin.jar:?]
                at com.bencodez.votingplugin.advancedcore.api.skull.SkullThread$ReadThread.run(SkullThread.java:57) ~[VotingPlugin.jar:?]
**Additional context**

**Comment by BenCodez** [comment]
you can disable preloadskulls in config.yml
