### ISSUE TITLE
MySQL issue.

### ISSUE THREAD

**Issue by Mrs-Feathers** [Ben12345rocks/VotingPlugin#1254]
**Versions**
spigot 1.19.2-R0.1-SNAPSHOT
votingplugin. 6.9.3

**Describe the bug**
The plugin seemingly does not support mysql, though i know it should because i've used it before.

**To Reproduce**
1. install plugin
2. have mysql database correctly setup and verified working with other servers
3. set up voting plugin for using mysql database
4. See error in console on boot, player login, etc.

**Expected behavior**
This plugin should, by default, connect to the mysql database and store/retrieve data.

**Screenshots/Configs**
Error:
`[18:41:06] [Timer-4/WARN]: java.lang.NullPointerException: Cannot invoke "com.bencodez.votingplugin.advancedcore.api.user.userstorage.mysql.MySQL.getUuids()" because the return value of "com.bencodez.votingplugin.advancedcore.AdvancedCorePlugin.getMysql()" is null
[18:41:06] [Timer-4/WARN]:      at com.bencodez.votingplugin.advancedcore.api.user.UserManager.getAllUUIDs(UserManager.java:104)
[18:41:06] [Timer-4/WARN]:      at com.bencodez.votingplugin.advancedcore.api.user.UserManager.getAllUUIDs(UserManager.java:73)
[18:41:06] [Timer-4/WARN]:      at com.bencodez.votingplugin.advancedcore.listeners.AdvancedCoreLoginEvent.isUserInStorage(AdvancedCoreLoginEvent.java:62)
[18:41:06] [Timer-4/WARN]:      at com.bencodez.votingplugin.advancedcore.listeners.PlayerJoinEvent.onJoin(PlayerJoinEvent.java:37)
[18:41:06] [Timer-4/WARN]:      at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
[18:41:06] [Timer-4/WARN]:      at java.base/java.lang.reflect.Method.invoke(Method.java:577)
[18:41:06] [Timer-4/WARN]:      at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306)
[18:41:06] [Timer-4/WARN]:      at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[18:41:06] [Timer-4/WARN]:      at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589)
[18:41:06] [Timer-4/WARN]:      at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576)
[18:41:06] [Timer-4/WARN]:      at com.bencodez.votingplugin.advancedcore.listeners.PlayerJoinEvent$1.run(PlayerJoinEvent.java:105)
[18:41:06] [Timer-4/WARN]:      at java.base/java.util.TimerThread.mainLoop(Timer.java:566)
[18:41:06] [Timer-4/WARN]:      at java.base/java.util.TimerThread.run(Timer.java:516)`
Config:
`/ VotingPlugin by BenCodez
/ Main Config
/ See wiki for help: 
/ https://github.com/BenCodez/VotingPlugin/wiki
/ Config is sorted in sections
/ Use Control + F to search with Notepad++
/ 
/ Valid Options:
/ - SQLITE 
/ - FLAT
/ - MYSQL
DataStorage: MYSQL

/ Information for mysql
/ See the end of the config for cache options
MySQL:
  Host: 'Database.correctdomain.tld'
  / Default port is 3306
  Port: 3306 
  Database: 'Minecraft'
  Username: 'CORRECTUSER'
  Password: 'CORRECTPASSWORD'
  / Max number of connections
  MaxConnections: 1
  / Table name prefix, for use with mutliple servers
  / Don't use with PLUGINMESSAGING bungee setup
  Prefix: 'VotingPlugin_'
  /UseSSL: true
  /PublicKeyRetrieval: false
  /MaxLifeTime: -1
  /Additional info on connection string
  /Line: ''
  /Attempt to use mariadb driver
  UseMariaDB: true`

**Additional context**
I'm willing to provide whatever info is needed to help get this solved for my server.

**Comment by BenCodez** [comment]
Send the config with pastebin and startup log as well
