### ISSUE TITLE
Could not pass event PlayerLoginEvent to VotingPlugin

### ISSUE THREAD

**Issue by rkfsociety** [Ben12345rocks/VotingPlugin#1258]
Using AdvancedCore 3.5.10' built on '2022-09-25 19:24
VotingPlugin version 6.9.5
This server is running Paper version git-Paper-194 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: ad3d357)
https://pastebin.pl/view/8e2164d7

**Comment by BenCodez** [comment]
A restart will fix it. Did you reload the plugin with plugman or something?

**Comment by rkfsociety** [comment]
this does not always happen, only when the player connects or disconnects, restarting the server does not help, I do not use plugman, it's stupid)))

**Comment by BenCodez** [comment]
Send your startup and the first error you get?

**Comment by rkfsociety** [comment]
I haven't noticed it for a long time, as soon as I see it, I'll write, after restarting it doesn't exist, it only appears when a player enters or exits the lobby.

**Comment by BenCodez** [comment]
If you get it again let me know. I'll try to track it down. I think it's some rare case that I haven't been able to track down just yet

**Comment by rkfsociety** [comment]
- [Mon 23:28:35 ERROR Minecraft] Could not pass event PlayerQuitEvent to VotingPlugin v6.9.5
java.lang.IllegalStateException: Timer already cancelled.
    at java.base/java.util.Timer.sched(Timer.java:409)
    at java.base/java.util.Timer.schedule(Timer.java:205)
    at VotingPlugin.jar//com.bencodez.votingplugin.listeners.PlayerJoinEvent.onPlayerQuit(PlayerJoinEvent.java:77)
    at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor291.execute(Unknown Source)
    at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75)
    at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:670)
    at net.minecraft.server.players.PlayerList.remove(PlayerList.java:627)
    at net.minecraft.server.players.PlayerList.remove(PlayerList.java:612)
    at net.minecraft.server.network.ServerGamePacketListenerImpl.onDisconnect(ServerGamePacketListenerImpl.java:2127)
    at net.minecraft.server.network.ServerGamePacketListenerImpl.onDisconnect(ServerGamePacketListenerImpl.java:2107)
    at net.minecraft.network.Connection.handleDisconnection(Connection.java:769)
    at net.minecraft.server.network.ServerConnectionListener.tick(ServerConnectionListener.java:253)
    at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1565)
    at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:446)
    at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1397)
    at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1173)
    at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305)
    at java.base/java.lang.Thread.run(Thread.java:833)
  [Mon 23:28:35 INFO  Server] Ben9 left the game

**Comment by rkfsociety** [comment]
- [Mon 23:28:08 ERROR Minecraft] Could not pass event PlayerLoginEvent to VotingPlugin v6.9.5
java.lang.IllegalStateException: Timer already cancelled.
    at java.base/java.util.Timer.sched(Timer.java:409)
    at java.base/java.util.Timer.schedule(Timer.java:205)
    at VotingPlugin.jar//com.bencodez.votingplugin.advancedcore.listeners.PlayerJoinEvent.onPlayerLogin(PlayerJoinEvent.java:64)
    at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor283.execute(Unknown Source)
    at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75)
    at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:670)
    at net.minecraft.server.players.PlayerList.canPlayerLogin(PlayerList.java:788)
    at net.minecraft.server.network.ServerLoginPacketListenerImpl.handleAcceptedLogin(ServerLoginPacketListenerImpl.java:180)
    at net.minecraft.server.network.ServerLoginPacketListenerImpl.tick(ServerLoginPacketListenerImpl.java:91)
    at net.minecraft.network.Connection.tick(Connection.java:568)
    at net.minecraft.server.network.ServerConnectionListener.tick(ServerConnectionListener.java:233)
    at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1565)
    at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:446)
    at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1397)
    at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1173)
    at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305)
    at java.base/java.lang.Thread.run(Thread.java:833)
  [Mon 23:28:08 INFO  Server] Ben9 joined the game

**Comment by BenCodez** [comment]
https://bencodez.com/job/VotingPlugin/
Does this help?

**Comment by rkfsociety** [comment]
so far, everything is fine
