### ISSUE TITLE
Message in console upon start / vote

### ISSUE THREAD

**Issue by DLmass** [Ben12345rocks/VotingPlugin#1265]
**Versions**
6.10.0 and Paper version git-Paper-373 (MC: 1.19.3)

**Describe the bug**
This message show up even though the plugin is configured properly - "Detected an issue with voting sites, check the server startup log for more details: https://github.com/BenCodez/VotingPlugin/wiki/Votifier-Troubleshooting"

I removed everything else since there is no way to reproduce it as well none additional information.

**Comment by DLmass** [comment]
No vote has been recieved from Minecraft-MP_com, may be an invalid service site. Please read: https://github.com/BenCodez/VotingPlugin/wiki/Votifier-Troubleshooting

--------------------------

[Sun 13:10:02 ERROR Votifier] Unable to process vote from /27.124.32.155:49038
com.vexsoftware.votifier.io.netty.handler.codec.DecoderException: com.vexsoftware.votifier.util.QuietException: Could not decrypt data from /27.124.32.155:49038 as it is too long. Attack?
    at nuvotifier.jar//com.vexsoftware.votifier.io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:471)
    at nuvotifier.jar//com.vexsoftware.votifier.io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
    at nuvotifier.jar//com.vexsoftware.votifier.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
    at nuvotifier.jar//com.vexsoftware.votifier.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
    at nuvotifier.jar//com.vexsoftware.votifier.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
    at nuvotifier.jar//com.vexsoftware.votifier.io.netty.handler.codec.ByteToMessageDecoder.handlerRemoved(ByteToMessageDecoder.java:253)
    at nuvotifier.jar//com.vexsoftware.votifier.io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:508)
    at nuvotifier.jar//com.vexsoftware.votifier.io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:440)
    at nuvotifier.jar//com.vexsoftware.votifier.io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
    at nuvotifier.jar//com.vexsoftware.votifier.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
    at nuvotifier.jar//com.vexsoftware.votifier.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
    at nuvotifier.jar//com.vexsoftware.votifier.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
    at n

**Comment by BenCodez** [comment]
Reset your keys by deleting the keys folder and resetup votifier with the new keys
