### ISSUE TITLE
MariaDB error

### ISSUE THREAD

**Issue by IsMeDark** [Ben12345rocks/VotingPlugin#1294]
com.bencodez.votingplugin.advancedcore.hikari.HikariDataSource]: HikariPool-1 - Starting...
[16:09:45 ERROR] [com.bencodez.votingplugin.advancedcore.hikari.pool.HikariPool]: HikariPool-1 - Exception during pool initialization.
java.sql.SQLException: Unknown system variable 'transaction_isolation'
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:130) ~[server.jar:git:Waterfall-Bootstrap:1.20-R0.1-SNAPSHOT:a6203d6:unknown]
        at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122) ~[server.jar:git:Waterfall-Bootstrap:1.20-R0.1-SNAPSHOT:a6203d6:unknown]
        at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:825) ~[server.jar:git:Waterfall-Bootstrap:1.20-R0.1-SNAPSHOT:a6203d6:unknown]
        at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:446) ~[server.jar:git:Waterfall-Bootstrap:1.20-R0.1-SNAPSHOT:a6203d6:unknown]
        at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:239) ~[server.jar:git:Waterfall-Bootstrap:1.20-R0.1-SNAPSHOT:a6203d6:unknown]
        at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:188) ~[server.jar:git:Waterfall-Bootstrap:1.20-R0.1-SNAPSHOT:a6203d6:unknown]
        at com.bencodez.votingplugin.advancedcore.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138) ~[?:?]
        at com.bencodez.votingplugin.advancedcore.hikari.pool.PoolBase.newConnection(PoolBase.java:353) ~[?:?]
        at com.bencodez.votingplugin.advancedcore.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:201) ~[?:?]
        at com.bencodez.votingplugin.advancedcore.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:473) ~[?:?]
        at com.bencodez.votingplugin.advancedcore.hikari.pool.HikariPool.checkFailFast(HikariPool.java:562) ~[?:?]
        at com.bencodez.votingplugin.advancedcore.hikari.pool.HikariPool.<init>(HikariPool.java:115) ~[?:?]
        at com.bencodez.votingplugin.advancedcore.hikari.HikariDataSource.<init>(HikariDataSource.java:81) ~[?:?]
        at com.bencodez.votingplugin.advancedcore.api.user.userstorage.mysql.api.ConnectionManager.open(ConnectionManager.java:211) ~[?:?]
        at com.bencodez.votingplugin.advancedcore.api.user.userstorage.mysql.api.MySQL.connect(MySQL.java:39) ~[?:?]
        at com.bencodez.votingplugin.advancedcore.bungeeapi.mysql.BungeeMySQL.<init>(BungeeMySQL.java:73) ~[?:?]
        at com.bencodez.votingplugin.bungee.VotingPluginBungee$1.<init>(VotingPluginBungee.java:289) ~[?:?]
        at com.bencodez.votingplugin.bungee.VotingPluginBungee.loadMysql(VotingPluginBungee.java:289) ~[?:?]
        at com.bencodez.votingplugin.bungee.VotingPluginBungee.onEnable(VotingPluginBungee.java:560) ~[?:?]
        at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:357) ~[server.jar:git:Waterfall-Bootstrap:1.20-R0.1-SNAPSHOT:a6203d6:unknown]
        at net.md_5.bungee.BungeeCord.start(BungeeCord.java:311) ~[server.jar:git:Waterfall-Bootstrap:1.20-R0.1-SNAPSHOT:a6203d6:unknown]
        at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:52) ~[server.jar:git:Waterfall-Bootstrap:1.20-R0.1-SNAPSHOT:a6203d6:unknown]
        at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15) ~[server.jar:git:Waterfall-Bootstrap:1.20-R0.1-SNAPSHOT:a6203d6:unknown]
[16:09:45 ERROR]: com.bencodez.votingplugin.advancedcore.hikari.pool.HikariPool$PoolInitializationException: Failed to initialize pool: Unknown system variable 'transaction_isolation'
[16:09:45 ERROR]:       at com.bencodez.votingplugin.advancedcore.hikari.pool.HikariPool.throwPoolInitializationException(HikariPool.java:597)
[16:09:45 ERROR]:       at com.bencodez.votingplugin.advancedcore.hikari.pool.HikariPool.checkFailFast(HikariPool.java:576)
[16:09:45 ERROR]:       at com.bencodez.votingplugin.advancedcore.hikari.pool.HikariPool.<init>(HikariPool.java:115)
[16:09:45 ERROR]:       at com.bencodez.votingplugin.advancedcore.hikari.HikariDataSource.<init>(HikariDataSource.java:81)
[16:09:45 ERROR]:       at com.bencodez.votingplugin.advancedcore.api.user.userstorage.mysql.api.ConnectionManager.open(ConnectionManager.java:211)
[16:09:45 ERROR]:       at com.bencodez.votingplugin.advancedcore.api.user.userstorage.mysql.api.MySQL.connect(MySQL.java:39)
[16:09:45 ERROR]:       at com.bencodez.votingplugin.advancedcore.bungeeapi.mysql.BungeeMySQL.<init>(BungeeMySQL.java:73)
[16:09:45 ERROR]:       at com.bencodez.votingplugin.bungee.VotingPluginBungee$1.<init>(VotingPluginBungee.java:289)
[16:09:45 ERROR]:       at com.bencodez.votingplugin.bungee.VotingPluginBungee.loadMysql(VotingPluginBungee.java:289)
[16:09:45 ERROR]:       at com.bencodez.votingplugin.bungee.VotingPluginBungee.onEnable(VotingPluginBungee.java:560)
[16:09:45 ERROR]:       at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:357)
[16:09:45 ERROR]:       at net.md_5.bungee.BungeeCord.start(BungeeCord.java:311)
[16:09:45 ERROR]:       at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:52)
[16:09:45 ERROR]:       at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
[16:09:45 ERROR]: Caused by: java.sql.SQLException: Unknown system variable 'transaction_isolation'
[16:09:45 ERROR]:       at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:130)
[16:09:45 ERROR]:       at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
[16:09:45 ERROR]:       at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:825)
[16:09:45 ERROR]:       at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:446)
[16:09:45 ERROR]:       at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:239)
[16:09:45 ERROR]:       at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:188)
[16:09:45 ERROR]:       at com.bencodez.votingplugin.advancedcore.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)
[16:09:45 ERROR]:       at com.bencodez.votingplugin.advancedcore.hikari.pool.PoolBase.newConnection(PoolBase.java:353)
[16:09:45 ERROR]:       at com.bencodez.votingplugin.advancedcore.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:201)
[16:09:45 ERROR]:       at com.bencodez.votingplugin.advancedcore.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:473)
[16:09:45 ERROR]:       at com.bencodez.votingplugin.advancedcore.hikari.pool.HikariPool.checkFailFast(HikariPool.java:562)
[16:09:45 ERROR]:       ... 12 more
[16:09:45 INFO] [com.bencodez.votingplugin.advancedcore.hikari.HikariDataSource]: HikariPool-2 - Starting...
[16:09:45 INFO] [com.bencodez.votingplugin.advancedcore.hikari.HikariDataSource]: HikariPool-4 - Starting...
[16:09:45 INFO] [com.bencodez.votingplugin.advancedcore.hikari.HikariDataSource]: HikariPool-3 - Starting...
[16:09:45 ERROR] [com.bencodez.votingplugin.advancedcore.hikari.pool.HikariPool]: HikariPool-4 - Exception during pool initialization.
java.sql.SQLException: Unknown system variable 'transaction_isolation'
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:130) ~[server.jar:git:Waterfall-Bootstrap:1.20-R0.1-SNAPSHOT:a6203d6:unknown]
        at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122) ~[server.jar:git:Waterfall-Bootstrap:1.20-R0.1-SNAPSHOT:a6203d6:unknown]
        at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:825) ~[server.jar:git:Waterfall-Bootstrap:1.20-R0.1-SNAPSHOT:a6203d6:unknown]
        at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:446) ~[server.jar:git:Waterfall-Bootstrap:1.20-R0.1-SNAPSHOT:a6203d6:unknown]
        at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:239) ~[server.jar:git:Waterfall-Bootstrap:1.20-R0.1-SNAPSHOT:a6203d6:unknown]
        at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:188) ~[server.jar:git:Waterfall-Bootstrap:1.20-R0.1-SNAPSHOT:a6203d6:unknown]

**Comment by IsMeDark** [comment]
I have activated
UseMariaDB: true

**Comment by BenCodez** [comment]
Update mariadb, it's a bug in mariadb

**Comment by IsMeDark** [comment]
I don't think it's a mariadb error, I'm 5 plugins in my bungeecord that use the same mysql and they work perfectly

**Comment by BenCodez** [comment]
I don't know how to fix it and I know updating mariadb fixes it.

I've gotten this message a lot lately and this is the only fix that I know of.
