### ISSUE TITLE
No enum constant org.bukkit.Sound.NONE

### ISSUE THREAD

**Issue by x1p** [Ben12345rocks/VotingPlugin#1296]
**Versions**
VotingPlugin 6.14
Purpur build 1985 (MC: 1.19.4)

**Describe the bug**
Player issued server command: /vote
```
[09:33:20] [Craft Scheduler Thread - 316 - VotingPlugin/WARN]: java.lang.IllegalArgumentException: No enum constant org.bukkit.Sound.NONE
[09:33:20] [Craft Scheduler Thread - 316 - VotingPlugin/WARN]: 	at java.base/java.lang.Enum.valueOf(Enum.java:273)
[09:33:20] [Craft Scheduler Thread - 316 - VotingPlugin/WARN]: 	at org.bukkit.Sound.valueOf(Sound.java:14)
[09:33:20] [Craft Scheduler Thread - 316 - VotingPlugin/WARN]: 	at VotingPlugin-6.14.jar//com.bencodez.votingplugin.advancedcore.AdvancedCoreConfigOptions.getClickSoundSound(AdvancedCoreConfigOptions.java:43)
[09:33:20] [Craft Scheduler Thread - 316 - VotingPlugin/WARN]: 	at VotingPlugin-6.14.jar//com.bencodez.votingplugin.advancedcore.api.inventory.BInventory.playSound(BInventory.java:632)
[09:33:20] [Craft Scheduler Thread - 316 - VotingPlugin/WARN]: 	at VotingPlugin-6.14.jar//com.bencodez.votingplugin.advancedcore.api.inventory.BInventory.onClick(BInventory.java:492)
[09:33:20] [Craft Scheduler Thread - 316 - VotingPlugin/WARN]: 	at VotingPlugin-6.14.jar//com.bencodez.votingplugin.advancedcore.api.inventory.BInventoryListener$2.run(BInventoryListener.java:97)
[09:33:20] [Craft Scheduler Thread - 316 - VotingPlugin/WARN]: 	at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftTask.run(CraftTask.java:101)
[09:33:20] [Craft Scheduler Thread - 316 - VotingPlugin/WARN]: 	at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[09:33:20] [Craft Scheduler Thread - 316 - VotingPlugin/WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[09:33:20] [Craft Scheduler Thread - 316 - VotingPlugin/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[09:33:20] [Craft Scheduler Thread - 316 - VotingPlugin/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[09:33:20] [Craft Scheduler Thread - 316 - VotingPlugin/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
```
**To Reproduce**
I'm not sure how to reproduce. I excuted it several times on different servers with the same setup and it didn't happen again.

**Expected behavior**
No errors

**Screenshots/Configs**
Not applicable

**Additional context**

**Comment by BenCodez** [comment]
This fix it? https://bencodez.com/job/VotingPlugin/

**Comment by x1p** [comment]
I'm happy to try. However, since I don't know how to reproduce it and everything works as normal, I can only wait and see if it happens again or not.

**Comment by BenCodez** [comment]
just click on the gui, I fixed it a few a bit ago

**Comment by x1p** [comment]
Oh I see. Clicking on the gui triggers it indeed :)

**Comment by BenCodez** [comment]
Yeah, I redid some background code and forget to include the handling for no sound. Doesn't break anything though

**Comment by x1p** [comment]
Fixed indeed \o/

**Comment by BenCodez** [comment]
Good :)
