### ISSUE TITLE
MYSQL Problem

### ISSUE THREAD

**Issue by witcharon** [Ben12345rocks/VotingPlugin#1301]
**Versions**
VotingPlugin: v6.14 Paper: 1.20.1

**Describe the bug**
I tried to set up Bungee, but the plugin is not connecting to the MYSQL database

**Screenshots/Configs**
![image](https://github.com/BenCodez/VotingPlugin/assets/114762286/b3c23a83-203f-4bf2-9abf-2eb705a96193)

**Additional context**
`[10:38:36 INFO]: [com.bencodez.votingplugin.advancedcore.hikari.HikariDataSource] HikariPool-1 - Starting...
[10:38:36 ERROR]: [com.bencodez.votingplugin.advancedcore.hikari.pool.HikariPool] HikariPool-1 - Exception during pool initialization.
java.sql.SQLSyntaxErrorException: Access denied for user 'u20770_Gi9Mh82ngu'@'%' to database 'null'
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:121) ~[mysql-connector-j-8.0.33.jar:8.0.33]
        at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122) ~[mysql-connector-j-8.0.33.jar:8.0.33]
        at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:825) ~[mysql-connector-j-8.0.33.jar:8.0.33]
        at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:446) ~[mysql-connector-j-8.0.33.jar:8.0.33]
        at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:239) ~[mysql-connector-j-8.0.33.jar:8.0.33]
        at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:188) ~[mysql-connector-j-8.0.33.jar:8.0.33]
        at com.bencodez.votingplugin.advancedcore.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138) ~[VotingPlugin.jar:?]
        at com.bencodez.votingplugin.advancedcore.hikari.pool.PoolBase.newConnection(PoolBase.java:353) ~[VotingPlugin.jar:?]
        at com.bencodez.votingplugin.advancedcore.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:201) ~[VotingPlugin.jar:?]
        at com.bencodez.votingplugin.advancedcore.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:473) ~[VotingPlugin.jar:?]
        at com.bencodez.votingplugin.advancedcore.hikari.pool.HikariPool.checkFailFast(HikariPool.java:562) ~[VotingPlugin.jar:?]
        at com.bencodez.votingplugin.advancedcore.hikari.pool.HikariPool.<init>(HikariPool.java:115) ~[VotingPlugin.jar:?]
        at com.bencodez.votingplugin.advancedcore.hikari.HikariDataSource.<init>(HikariDataSource.java:81) ~[VotingPlugin.jar:?]
        at com.bencodez.votingplugin.advancedcore.api.user.userstorage.mysql.api.ConnectionManager.open(ConnectionManager.java:211) ~[VotingPlugin.jar:?]
        at com.bencodez.votingplugin.advancedcore.api.user.userstorage.mysql.api.MySQL.connect(MySQL.java:39) ~[VotingPlugin.jar:?]
        at com.bencodez.votingplugin.advancedcore.api.user.userstorage.mysql.MySQL.<init>(MySQL.java:90) ~[VotingPlugin.jar:?]
        at com.bencodez.votingplugin.advancedcore.AdvancedCorePlugin.loadUserAPI(AdvancedCorePlugin.java:754) ~[VotingPlugin.jar:?]
        at com.bencodez.votingplugin.advancedcore.AdvancedCorePlugin.loadConfig(AdvancedCorePlugin.java:451) ~[VotingPlugin.jar:?]
        at com.bencodez.votingplugin.advancedcore.AdvancedCorePlugin.loadHook(AdvancedCorePlugin.java:499) ~[VotingPlugin.jar:?]
        at com.bencodez.votingplugin.advancedcore.AdvancedCorePlugin.onEnable(AdvancedCorePlugin.java:929) ~[VotingPlugin.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189) ~[paper-1.20.1.jar:git-Paper-167]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.20.1.jar:git-Paper-167]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:640) ~[paper-1.20.1.jar:git-Paper-167]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:551) ~[paper-1.20.1.jar:git-Paper-167]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:636) ~[paper-1.20.1.jar:git-Paper-167]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:435) ~[paper-1.20.1.jar:git-Paper-167]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:308) ~[paper-1.20.1.jar:git-Paper-167]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1101) ~[paper-1.20.1.jar:git-Paper-167]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[paper-1.20.1.jar:git-Paper-167]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[10:38:37 WARN]: com.bencodez.votingplugin.advancedcore.hikari.pool.HikariPool$PoolInitializationException: Failed to initialize pool: Access denied for user 'u20770_Gi9Mh82ngu'@'%' to database 'null'
[10:38:37 WARN]:        at VotingPlugin.jar//com.bencodez.votingplugin.advancedcore.hikari.pool.HikariPool.throwPoolInitializationException(HikariPool.java:597)
[10:38:37 WARN]:        at VotingPlugin.jar//com.bencodez.votingplugin.advancedcore.hikari.pool.HikariPool.checkFailFast(HikariPool.java:576)
[10:38:37 WARN]:        at VotingPlugin.jar//com.bencodez.votingplugin.advancedcore.hikari.pool.HikariPool.<init>(HikariPool.java:115)
[10:38:37 WARN]:        at VotingPlugin.jar//com.bencodez.votingplugin.advancedcore.hikari.HikariDataSource.<init>(HikariDataSource.java:81)
[10:38:37 WARN]:        at VotingPlugin.jar//com.bencodez.votingplugin.advancedcore.api.user.userstorage.mysql.api.ConnectionManager.open(ConnectionManager.java:211)
[10:38:37 WARN]:        at VotingPlugin.jar//com.bencodez.votingplugin.advancedcore.api.user.userstorage.mysql.api.MySQL.connect(MySQL.java:39)
[10:38:37 WARN]:        at VotingPlugin.jar//com.bencodez.votingplugin.advancedcore.api.user.userstorage.mysql.MySQL.<init>(MySQL.java:90)
[10:38:37 WARN]:        at VotingPlugin.jar//com.bencodez.votingplugin.advancedcore.AdvancedCorePlugin.loadUserAPI(AdvancedCorePlugin.java:754)
[10:38:37 WARN]:        at VotingPlugin.jar//com.bencodez.votingplugin.advancedcore.AdvancedCorePlugin.loadConfig(AdvancedCorePlugin.java:451)
[10:38:37 WARN]:        at VotingPlugin.jar//com.bencodez.votingplugin.advancedcore.AdvancedCorePlugin.loadHook(AdvancedCorePlugin.java:499)
[10:38:37 WARN]:        at VotingPlugin.jar//com.bencodez.votingplugin.advancedcore.AdvancedCorePlugin.onEnable(AdvancedCorePlugin.java:929)
[10:38:37 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281)
[10:38:37 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189)
[10:38:37 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104)
[10:38:37 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507)
[10:38:37 WARN]:        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:640)
[10:38:37 WARN]:        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:551)
[10:38:37 WARN]:        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:636)
[10:38:37 WARN]:        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:435)
[10:38:37 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:308)
[10:38:37 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1101)
[10:38:37 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318)
[10:38:37 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[10:38:37 WARN]: Caused by: java.sql.SQLSyntaxErrorException: Access denied for user 'u20770_Gi9Mh82ngu'@'%' to database 'null'
[10:38:37 WARN]:        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:121)
[10:38:37 WARN]:        at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
[10:38:37 WARN]:        at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:825)
[10:38:37 WARN]:        at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:446)
[10:38:37 WARN]:        at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:239)
[10:38:37 WARN]:        at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:188)
[10:38:37 WARN]:        at VotingPlugin.jar//com.bencodez.votingplugin.advancedcore.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)
[10:38:37 WARN]:        at VotingPlugin.jar//com.bencodez.votingplugin.advancedcore.hikari.pool.PoolBase.newConnection(PoolBase.java:353)
[10:38:37 WARN]:        at VotingPlugin.jar//com.bencodez.votingplugin.advancedcore.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:201)
[10:38:37 WARN]:        at VotingPlugin.jar//com.bencodez.votingplugin.advancedcore.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:473)
[10:38:37 WARN]:        at VotingPlugin.jar//com.bencodez.votingplugin.advancedcore.hikari.pool.HikariPool.checkFailFast(HikariPool.java:562)
[10:38:37 WARN]:        ... 21 more
[10:38:37 WARN]: [VotingPlugin] Failed to connect to MySQL
[10:38:37 INFO]: [com.bencodez.votingplugin.advancedcore.hikari.HikariDataSource] HikariPool-2 - Starting...
[10:38:37 ERROR]: [com.bencodez.votingplugin.advancedcore.hikari.pool.HikariPool] HikariPool-2 - Exception during pool initialization.
java.sql.SQLSyntaxErrorException: Access denied for user 'u20770_Gi9Mh82ngu'@'%' to database 'null'
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:121) ~[mysql-connector-j-8.0.33.jar:8.0.33]
        at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122) ~[mysql-connector-j-8.0.33.jar:8.0.33]
        at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:825) ~[mysql-connector-j-8.0.33.jar:8.0.33]
        at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:446) ~[mysql-connector-j-8.0.33.jar:8.0.33]
        at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:239) ~[mysql-connector-j-8.0.33.jar:8.0.33]
        at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:188) ~[mysql-connector-j-8.0.33.jar:8.0.33]
        at com.bencodez.votingplugin.advancedcore.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138) ~[VotingPlugin.jar:?]
        at com.bencodez.votingplugin.advancedcore.hikari.pool.PoolBase.newConnection(PoolBase.java:353) ~[VotingPlugin.jar:?]
        at com.bencodez.votingplugin.advancedcore.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:201) ~[VotingPlugin.jar:?]
        at com.bencodez.votingplugin.advancedcore.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:473) ~[VotingPlugin.jar:?]
        at com.bencodez.votingplugin.advancedcore.hikari.pool.HikariPool.checkFailFast(HikariPool.java:562) ~[VotingPlugin.jar:?]
        at com.bencodez.votingplugin.advancedcore.hikari.pool.HikariPool.<init>(HikariPool.java:115) ~[VotingPlugin.jar:?]
        at com.bencodez.votingplugin.advancedcore.hikari.HikariDataSource.<init>(HikariDataSource.java:81) ~[VotingPlugin.jar:?]
        at com.bencodez.votingplugin.advancedcore.api.user.userstorage.mysql.api.ConnectionManager.open(ConnectionManager.java:211) ~[VotingPlugin.jar:?]
        at com.bencodez.votingplugin.advancedcore.api.user.userstorage.mysql.api.ConnectionManager.getConnection(ConnectionManager.java:79) ~[VotingPlugin.jar:?]
        at com.bencodez.votingplugin.advancedcore.api.user.userstorage.mysql.api.queries.Query.executeUpdate(Query.java:143) ~[VotingPlugin.jar:?]
        at com.bencodez.votingplugin.advancedcore.api.user.userstorage.mysql.MySQL.<init>(MySQL.java:95) ~[VotingPlugin.jar:?]
        at com.bencodez.votingplugin.advancedcore.AdvancedCorePlugin.loadUserAPI(AdvancedCorePlugin.java:754) ~[VotingPlugin.jar:?]
        at com.bencodez.votingplugin.advancedcore.AdvancedCorePlugin.loadConfig(AdvancedCorePlugin.java:451) ~[VotingPlugin.jar:?]
        at com.bencodez.votingplugin.advancedcore.AdvancedCorePlugin.loadHook(AdvancedCorePlugin.java:499) ~[VotingPlugin.jar:?]
        at com.bencodez.votingplugin.advancedcore.AdvancedCorePlugin.onEnable(AdvancedCorePlugin.java:929) ~[VotingPlugin.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189) ~[paper-1.20.1.jar:git-Paper-167]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.20.1.jar:git-Paper-167]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:640) ~[paper-1.20.1.jar:git-Paper-167]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:551) ~[paper-1.20.1.jar:git-Paper-167]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:636) ~[paper-1.20.1.jar:git-Paper-167]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:435) ~[paper-1.20.1.jar:git-Paper-167]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:308) ~[paper-1.20.1.jar:git-Paper-167]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1101) ~[paper-1.20.1.jar:git-Paper-167]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[paper-1.20.1.jar:git-Paper-167]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[10:38:37 WARN]: com.bencodez.votingplugin.advancedcore.hikari.pool.HikariPool$PoolInitializationException: Failed to initialize pool: Access denied for user 'u20770_Gi9Mh82ngu'@'%' to database 'null'
[10:38:37 WARN]:        at VotingPlugin.jar//com.bencodez.votingplugin.advancedcore.hikari.pool.HikariPool.throwPoolInitializationException(HikariPool.java:597)
[10:38:37 WARN]:        at VotingPlugin.jar//com.bencodez.votingplugin.advancedcore.hikari.pool.HikariPool.checkFailFast(HikariPool.java:576)
[10:38:37 WARN]:        at VotingPlugin.jar//com.bencodez.votingplugin.advancedcore.hikari.pool.HikariPool.<init>(HikariPool.java:115)
[10:38:37 WARN]:        at VotingPlugin.jar//com.bencodez.votingplugin.advancedcore.hikari.HikariDataSource.<init>(HikariDataSource.java:81)
[10:38:37 WARN]:        at VotingPlugin.jar//com.bencodez.votingplugin.advancedcore.api.user.userstorage.mysql.api.ConnectionManager.open(ConnectionManager.java:211)
[10:38:37 WARN]:        at VotingPlugin.jar//com.bencodez.votingplugin.advancedcore.api.user.userstorage.mysql.api.ConnectionManager.getConnection(ConnectionManager.java:79)
[10:38:37 WARN]:        at VotingPlugin.jar//com.bencodez.votingplugin.advancedcore.api.user.userstorage.mysql.api.queries.Query.executeUpdate(Query.java:143)
[10:38:37 WARN]:        at VotingPlugin.jar//com.bencodez.votingplugin.advancedcore.api.user.userstorage.mysql.MySQL.<init>(MySQL.java:95)
[10:38:37 WARN]:        at VotingPlugin.jar//com.bencodez.votingplugin.advancedcore.AdvancedCorePlugin.loadUserAPI(AdvancedCorePlugin.java:754)
[10:38:37 WARN]:        at VotingPlugin.jar//com.bencodez.votingplugin.advancedcore.AdvancedCorePlugin.loadConfig(AdvancedCorePlugin.java:451)
[10:38:37 WARN]:        at VotingPlugin.jar//com.bencodez.votingplugin.advancedcore.AdvancedCorePlugin.loadHook(AdvancedCorePlugin.java:499)
[10:38:37 WARN]:        at VotingPlugin.jar//com.bencodez.votingplugin.advancedcore.AdvancedCorePlugin.onEnable(AdvancedCorePlugin.java:929)
[10:38:37 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281)
[10:38:37 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189)
[10:38:37 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104)
[10:38:37 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507)
[10:38:37 WARN]:        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:640)
[10:38:37 WARN]:        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:551)
[10:38:37 WARN]:        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:636)
[10:38:37 WARN]:        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:435)
[10:38:37 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:308)
[10:38:37 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1101)
[10:38:37 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318)
[10:38:37 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[10:38:37 WARN]: Caused by: java.sql.SQLSyntaxErrorException: Access denied for user 'u20770_Gi9Mh82ngu'@'%' to database 'null'
[10:38:37 WARN]:        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:121)
[10:38:37 WARN]:        at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
[10:38:37 WARN]:        at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:825)
[10:38:37 WARN]:        at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:446)
[10:38:37 WARN]:        at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:239)
[10:38:37 WARN]:        at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:188)
[10:38:37 WARN]:        at VotingPlugin.jar//com.bencodez.votingplugin.advancedcore.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)
[10:38:37 WARN]:        at VotingPlugin.jar//com.bencodez.votingplugin.advancedcore.hikari.pool.PoolBase.newConnection(PoolBase.java:353)
[10:38:37 WARN]:        at VotingPlugin.jar//com.bencodez.votingplugin.advancedcore.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:201)
[10:38:37 WARN]:        at VotingPlugin.jar//com.bencodez.votingplugin.advancedcore.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:473)
[10:38:37 WARN]:        at VotingPlugin.jar//com.bencodez.votingplugin.advancedcore.hikari.pool.HikariPool.checkFailFast(HikariPool.java:562)
[10:38:37 WARN]:        at VotingPlugin.jar//com.bencodez.votingplugin.advancedcore.hikari.pool.HikariPool.<init>(HikariPool.java:115)
[10:38:37 WARN]:        at VotingPlugin.jar//com.bencodez.votingplugin.advancedcore.hikari.HikariDataSource.<init>(HikariDataSource.java:81)
[10:38:37 WARN]:        at VotingPlugin.jar//com.bencodez.votingplugin.advancedcore.api.user.userstorage.mysql.api.ConnectionManager.open(ConnectionManager.java:211)
[10:38:37 WARN]:        at VotingPlugin.jar//com.bencodez.votingplugin.advancedcore.api.user.userstorage.mysql.api.ConnectionManager.getConnection(ConnectionManager.java:79)
[10:38:37 WARN]:        at VotingPlugin.jar//com.bencodez.votingplugin.advancedcore.api.user.userstorage.mysql.api.queries.Query.executeUpdate(Query.java:143)
[10:38:37 WARN]:        at VotingPlugin.jar//com.bencodez.votingplugin.advancedcore.api.user.userstorage.mysql.MySQL.<init>(MySQL.java:95)
[10:38:37 WARN]:        at VotingPlugin.jar//com.bencodez.votingplugin.advancedcore.AdvancedCorePlugin.loadUserAPI(AdvancedCorePlugin.java:754)
[10:38:37 WARN]:        at VotingPlugin.jar//com.bencodez.votingplugin.advancedcore.AdvancedCorePlugin.loadConfig(AdvancedCorePlugin.java:451)
[10:38:37 WARN]:        at VotingPlugin.jar//com.bencodez.votingplugin.advancedcore.AdvancedCorePlugin.loadHook(AdvancedCorePlugin.java:499)
[10:38:37 WARN]:        at VotingPlugin.jar//com.bencodez.votingplugin.advancedcore.AdvancedCorePlugin.onEnable(AdvancedCorePlugin.java:929)
[10:38:37 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281)
[10:38:37 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189)
[10:38:37 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104)
[10:38:37 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507)
[10:38:37 WARN]:        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:640)
[10:38:37 WARN]:        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:551)
[10:38:37 WARN]:        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:636)
[10:38:37 WARN]:        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:435)
[10:38:37 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:308)
[10:38:37 WARN]:        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1101)
[10:38:37 WARN]:        ... 2 more
[10:38:37 ERROR]: Error occurred while enabling VotingPlugin v6.14 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "com.bencodez.votingplugin.advancedcore.hikari.HikariDataSource.getConnection()" because "this.dataSource" is null
        at com.bencodez.votingplugin.advancedcore.api.user.userstorage.mysql.api.ConnectionManager.getConnection(ConnectionManager.java:81) ~[VotingPlugin.jar:?]
        at com.bencodez.votingplugin.advancedcore.api.user.userstorage.mysql.api.queries.Query.executeUpdate(Query.java:143) ~[VotingPlugin.jar:?]
        at com.bencodez.votingplugin.advancedcore.api.user.userstorage.mysql.MySQL.<init>(MySQL.java:95) ~[VotingPlugin.jar:?]
        at com.bencodez.votingplugin.advancedcore.AdvancedCorePlugin.loadUserAPI(AdvancedCorePlugin.java:754) ~[VotingPlugin.jar:?]
        at com.bencodez.votingplugin.advancedcore.AdvancedCorePlugin.loadConfig(AdvancedCorePlugin.java:451) ~[VotingPlugin.jar:?]
        at com.bencodez.votingplugin.advancedcore.AdvancedCorePlugin.loadHook(AdvancedCorePlugin.java:499) ~[VotingPlugin.jar:?]
        at com.bencodez.votingplugin.advancedcore.AdvancedCorePlugin.onEnable(AdvancedCorePlugin.java:929) ~[VotingPlugin.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189) ~[paper-1.20.1.jar:git-Paper-167]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.20.1.jar:git-Paper-167]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:640) ~[paper-1.20.1.jar:git-Paper-167]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:551) ~[paper-1.20.1.jar:git-Paper-167]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:636) ~[paper-1.20.1.jar:git-Paper-167]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:435) ~[paper-1.20.1.jar:git-Paper-167]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:308) ~[paper-1.20.1.jar:git-Paper-167]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1101) ~[paper-1.20.1.jar:git-Paper-167]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[paper-1.20.1.jar:git-Paper-167]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[10:38:37 INFO]: [VotingPlugin] Disabling VotingPlugin v6.14
[10:38:37 ERROR]: Error occurred (in the plugin loader) while disabling VotingPlugin v6.14 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "com.bencodez.votingplugin.advancedcore.api.user.userstorage.mysql.MySQL.close()" because the return value of "com.bencodez.votingplugin.advancedcore.AdvancedCorePlugin.getMysql()" is null
        at com.bencodez.votingplugin.advancedcore.AdvancedCorePlugin.onDisable(AdvancedCorePlugin.java:885) ~[VotingPlugin.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:283) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugin(PaperPluginInstanceManager.java:224) ~[paper-1.20.1.jar:git-Paper-167]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.disablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.20.1.jar:git-Paper-167]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:537) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:193) ~[paper-1.20.1.jar:git-Paper-167]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.20.1.jar:git-Paper-167]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:640) ~[paper-1.20.1.jar:git-Paper-167]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:551) ~[paper-1.20.1.jar:git-Paper-167]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:636) ~[paper-1.20.1.jar:git-Paper-167]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:435) ~[paper-1.20.1.jar:git-Paper-167]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:308) ~[paper-1.20.1.jar:git-Paper-167]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1101) ~[paper-1.20.1.jar:git-Paper-167]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[paper-1.20.1.jar:git-Paper-167]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]`

**Comment by BenCodez** [comment]
Database has d's there
