### ISSUE TITLE
1.20.6 update Reflection bug / NFE

### ISSUE THREAD

**Issue by TheoMarque** [Ben12345rocks/VotingPlugin#1353]
**Versions**
latest, 6.16, paper 1.20.6 b51

**Describe the bug**
Paste a trace:

[22:26:03 WARN]: java.lang.ClassNotFoundException: org.bukkit.craftbukkit.craftbukkit.inventory.CraftItemStack
[22:26:03 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:197)
[22:26:03 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:164)
[22:26:03 WARN]:        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
[22:26:03 WARN]:        at java.base/java.lang.Class.forName0(Native Method)
[22:26:03 WARN]:        at java.base/java.lang.Class.forName(Class.java:529)
[22:26:03 WARN]:        at java.base/java.lang.Class.forName(Class.java:508)
[22:26:03 WARN]:        at io.papermc.reflectionrewriter.runtime.AbstractDefaultRulesReflectionProxy.forName(AbstractDefaultRulesReflectionProxy.java:68)
[22:26:03 WARN]:        at io.papermc.paper.pluginremap.reflect.PaperReflectionHolder.forName(Unknown Source)
[22:26:03 WARN]:        at VotingPlugin.jar//com.bencodez.votingplugin.advancedcore.nms.ReflectionUtils.getClassForName(ReflectionUtils.java:27)
[22:26:03 WARN]:        at VotingPlugin.jar//com.bencodez.votingplugin.advancedcore.api.skull.SkullHandler.load(SkullHandler.java:122)
[22:26:03 WARN]:        at VotingPlugin.jar//com.bencodez.votingplugin.advancedcore.AdvancedCorePlugin.loadHook(AdvancedCorePlugin.java:550)
[22:26:03 WARN]:        at VotingPlugin.jar//com.bencodez.votingplugin.advancedcore.AdvancedCorePlugin.onEnable(AdvancedCorePlugin.java:961)
[22:26:03 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:287)
[22:26:03 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202)
[22:26:03 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109)
[22:26:03 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:519)
[22:26:03 WARN]:        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:639)
[22:26:03 WARN]:        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:551)
[22:26:03 WARN]:        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:682)
[22:26:03 WARN]:        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:441)
[22:26:03 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:324)
[22:26:03 WARN]:        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1140)
[22:26:03 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:326)
[22:26:03 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1570)
[22:26:03 ERROR]: Error occurred while enabling VotingPlugin v6.16 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "java.lang.Class.getName()" because "clazz" is null
        at io.papermc.paper.pluginremap.reflect.PaperReflection.mapDeclaredMethodName(PaperReflection.java:62) ~[paper-1.20.6.jar:git-Paper-51]
        at io.papermc.reflectionrewriter.runtime.AbstractDefaultRulesReflectionProxy.getDeclaredMethod(AbstractDefaultRulesReflectionProxy.java:95) ~[reflection-rewriter-runtime-0.0.1.jar:?]
        at io.papermc.paper.pluginremap.reflect.PaperReflectionHolder.getDeclaredMethod(Unknown Source) ~[paper-1.20.6.jar:git-Paper-51]
        at VotingPlugin.jar/com.bencodez.votingplugin.advancedcore.api.skull.SkullHandler.load(SkullHandler.java:131) ~[VotingPlugin.jar:?]
        at VotingPlugin.jar/com.bencodez.votingplugin.advancedcore.AdvancedCorePlugin.loadHook(AdvancedCorePlugin.java:550) ~[VotingPlugin.jar:?]
        at VotingPlugin.jar/com.bencodez.votingplugin.advancedcore.AdvancedCorePlugin.onEnable(AdvancedCorePlugin.java:961) ~[VotingPlugin.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:287) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[paper-1.20.6.jar:git-Paper-51]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.20.6.jar:git-Paper-51]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:519) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:639) ~[paper-1.20.6.jar:git-Paper-51]
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:551) ~[paper-1.20.6.jar:git-Paper-51]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:682) ~[paper-1.20.6.jar:git-Paper-51]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:441) ~[paper-1.20.6.jar:git-Paper-51]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:324) ~[paper-1.20.6.jar:git-Paper-51]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1140) ~[paper-1.20.6.jar:git-Paper-51]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:326) ~[paper-1.20.6.jar:git-Paper-51]
        at java.base/java.lang.Thread.run(Thread.java:1570) ~[?:?]
[22:26:03 INFO]: [VotingPlugin] Disabling VotingPlugin v6.16
[22:26:03 INFO]: [VotingPlugin] Allowing background tasks to finish, this could take up to 5 seconds
[22:26:03 ERROR]: Error occurred while disabling VotingPlugin v6.16
java.lang.NullPointerException: Cannot invoke "java.util.concurrent.ScheduledExecutorService.shutdown()" because "this.voteTimer" is null
        at VotingPlugin.jar/com.bencodez.votingplugin.VotingPluginMain.onUnLoad(VotingPluginMain.java:1311) ~[VotingPlugin.jar:?]
        at VotingPlugin.jar/com.bencodez.votingplugin.advancedcore.AdvancedCorePlugin.onDisable(AdvancedCorePlugin.java:937) ~[VotingPlugin.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:290) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugin(PaperPluginInstanceManager.java:237) ~[paper-1.20.6.jar:git-Paper-51]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.disablePlugin(PaperPluginManagerImpl.java:114) ~[paper-1.20.6.jar:git-Paper-51]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:549) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:206) ~[paper-1.20.6.jar:git-Paper-51]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.20.6.jar:git-Paper-51]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:519) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:639) ~[paper-1.20.6.jar:git-Paper-51]
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:551) ~[paper-1.20.6.jar:git-Paper-51]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:682) ~[paper-1.20.6.jar:git-Paper-51]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:441) ~[paper-1.20.6.jar:git-Paper-51]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:324) ~[paper-1.20.6.jar:git-Paper-51]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1140) ~[paper-1.20.6.jar:git-Paper-51]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:326) ~[paper-1.20.6.jar:git-Paper-51]
        at java.base/java.lang.Thread.run(Thread.java:1570) ~[?:?]

**To Reproduce**

Just start server.

**Comment by BenCodez** [comment]
Issue is currently only present on paper, it works fine on spigot

**Comment by BenCodez** [comment]
Does this happen to fix it though? https://bencodez.com/job/VotingPlugin/

**Comment by TheoMarque** [comment]
Yes, #1243 fixed on paper! Thx!
