### ISSUE TITLE
Unable to decrypt vote record on world join and vote

### ISSUE THREAD

**Issue by LadyHaley** [Ben12345rocks/VotingPlugin#1372]
**Versions**
Plugin version and spigot version
Paper 1.21 Build 105
Voting Plugin 6.17
VotifierPlus 1.3

**Describe the bug**

Unable to decrypt vote record error msg

I have regenerated my public and secret keys to no change. My understanding is that I dont need to set and forwarding settings in votifierplus while using voting plugin. I have configured all the settings listed on the votingplugin bungeecord setup page, and verified that all servers are using mysql, the votingpluginbungee command can connect with the servers on the proxy

**To Reproduce**

No errors show in velocity proxy when I launch it, the console shows the following

`[14:09:45 INFO] [votifierplus]: Debug: 0.0.0.0:25570
[14:09:45 INFO] [votifierplus]: Votifier enabled.
[14:09:45 INFO] [votifierplus]: VotingPlugin velocity loaded, Internal Jar Version: 1.3
[14:09:45 INFO] [com.bencodez.votingplugin.advancedcore.hikari.HikariDataSource]: HikariPool-1 - Starting...
[14:09:45 INFO] [com.bencodez.votingplugin.advancedcore.hikari.HikariDataSource]: HikariPool-1 - Start completed.
[14:09:46 INFO] [AdvancedServerList]: You are running the latest version!
[14:09:46 INFO] [votingplugin]: VotingPlugin velocity loaded, method: PLUGINMESSAGING, PluginMessagingVersion: 1, Internal Jar Version: 6.17`

Then once I join a world and when I send a vote it shows me this error
`[14:14:19 WARN] [votifierplus]: Unable to decrypt vote record. Make sure that that your public key
[14:14:19 WARN] [votifierplus]: matches the one you gave the server list.
[14:14:19 ERROR]: javax.crypto.BadPaddingException: Padding error in decryption
[14:14:19 ERROR]: 	at java.base/com.sun.crypto.provider.RSACipher.doFinal(RSACipher.java:383)
[14:14:19 ERROR]: 	at java.base/com.sun.crypto.provider.RSACipher.engineDoFinal(RSACipher.java:419)
[14:14:19 ERROR]: 	at java.base/javax.crypto.Cipher.doFinal(Cipher.java:2244)
[14:14:19 ERROR]: 	at com.vexsoftware.votifier.crypto.RSA.decrypt(RSA.java:65)
[14:14:19 ERROR]: 	at com.vexsoftware.votifier.net.VoteReceiver.run(VoteReceiver.java:146)
`
 I used https://minestatus.net/tools/votifier to test the connection, it says its only able to send a votifier 1 vote to the server, I would have assumed it would send a v2 vote if it could. 

**Expected behavior**
Vote goes through successfully and no error on world join

**Screenshots/Configs**
If applicable, add screenshots to help explain your problem and/or configs relating to the issue.
[Configs.zip](https://github.com/user-attachments/files/16398121/Configs.zip)

**Additional context**

This is a clean server, with fresh config files

**Comment by BenCodez** [comment]
Try going here and generating keys (set to 2048 bit) and see if that works: https://www.devglan.com/online-tools/rsa-encryption-decryption

**Comment by LadyHaley** [comment]
The vote is now going through to the server successfully, however the vote is still sent as a v1 vote and the error still occurs on world join. unless theres some serious functionality that ill miss from a v2 vote, I think this solution will work for me

**Comment by BenCodez** [comment]
VotingPlugin doesn't care about a v1 vote vs v2 vote
